spring:
  datasource:
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/happyrecipek?serverTimezone=UTC
    username: root
    password: cjsekd13!
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
server:
  port: 8080
logging:
  level:
    sql: debug
    web: debug    root: debug