spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url : jdbc:mysql://localhost:3306/happyrecipek?serverTimezone=UTC
    username: root
    password: cjsekd13!
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  #Security Queries Descript
  queries:
    users-query: select email, password, active from user where email=?
server:
  context-path: /
  port: 8080
security:  basic:    enabled: false